version: "3"

services:
  postgres:
    image: postgres:11
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  cam-workflow:
    image: camunda/camunda-bpm-platform:7.18.0
    container_name: cam-workflow
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  cam-external-client:
    build: .
    container_name: cam-external-client
    depends_on:
      - cam-workflow
    environment:
      - ENDPOINT=cam-workflow:8080
      - TOPIC=topicName

volumes:
  pgdata:
    driver: local
