version: "3"

services:
  postgres:
    image: postgres:11
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  camunda-workflow:
    image: camunda/camunda-bpm-platform:7.18.0
    container_name: camunda-workflow
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  camunda-ext-client:
    build: worker/
    container_name: camunda-ext-client
    depends_on:
      - camunda-workflow
    environment:
      - ENDPOINT=camunda-workflow:8080
      - TOPIC=identifyCountries;navigateCountries

  pais_ticket_broker:
    build: ticket_broker/
    container_name: ticket_broker
    depends_on:
      - camunda-workflow
    environment:
      - ENDPOINT=camunda-workflow:8080
      - TOPIC=findRoutes;suggestRoutes;findTickets;buyTickets
volumes:
  pgdata:
    driver: local
