version: "3"

services:
  postgres:
    image: postgres:11
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  camunda_workflow:
    image: camunda/camunda-bpm-platform:7.13.0
    container_name: camunda_workflow
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  camunda_external_client:
    build: .
    container_name: camunda_external_client
    depends_on:
      - camunda_workflow

volumes:
  pgdata:
    driver: local